import { Metadata } from 'next'
import "../../global.css"
import { Providers } from './provider';
import { AppProvider } from '@/packages/providers/AppProvider';

export const metadata: Metadata = {
    title: ". : : Alloy App : : .",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.ico',
    }
};

export default function PublicRootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="light">
            <body>
                <AppProvider>
                    <Providers>
                        {children}
                    </Providers>
                </AppProvider>
            </body>
        </html>
    )
}
